### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by pranay1208** [ckcr4lyf/stdinman#1]
I have noticed a very high audio volume when the bot joins my voice channel. Would it be possible to introduce some kind of volume control?

Thank you for your time and consideration

**Comment by ckcr4lyf** [comment]
Thanks for opening this issue.

Since the goal of `stdinman` is to purely facilitate in piping raw audio into discord with minimal config, I won't add a volume option. I can recommend:

## Controlling input volume via ffmpeg: https://trac.ffmpeg.org/wiki/AudioVolume#Changingvolume

Examples:

```
# increase volume by 10dB
ffmpeg -i input.wav -filter:a "volume=10dB" output.wav
# decrease volume by 5dB
ffmpeg -i input.wav -filter:a "volume=-5dB" output.wav
```

basically use the `-filter:a` flag.

## Changing the volume of the bot

Discord allows you to change the volume of a user (or bot), you can reduce this. It should remember it for the next time the bot connects.
